### ISSUE TITLE
I want to download these wesites template but not able to see download option here

### ISSUE THREAD

**Issue by satyendragupta** [learning-zone/website-templates#15]

**Comment by nparashar150** [comment]
- Open the website-template repo and click on code and download zip.
- Another way is open shell type git clone <repo-name> 
  You will have the repo then you can look for the code inside them.

**Comment by satyendragupta** [comment]
Hi,

I want to clone/download only the education bootstrap website templates not
the whole 150 website..so is there any way to download or clone these
specific website.while open the education website there is no option to
clone or download

Thanks

**Comment by learning-zone** [comment]
Hi Satyendragupta,

You can use [Github Desktop software](https://desktop.github.com/) for cloning specific website template.

Thanks
