### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by DrSloth** [learning-zone/website-templates#16]
Hello there.
This is really nice work and a good place to get inspiration from. My question is what the licenses of the templates are.
Would i be allowed to use and alter them for personal projects? 
Would i be allowed to use and alter them for  commercial products?

Thanks in advance and keep up the nice work.

**Comment by learning-zone** [comment]
Hi DrSloth,

These website templates are just for learning purpose only. Please read copyrights available inside templets as readme.txt file before using it for commercial projects.

Thanks
