### ISSUE TITLE
Dreamy: font

### ISSUE THREAD

**Issue by NoemieSch** [learning-zone/website-templates#48]
The serif font in the Dreamy template is not very legible. At a lower resolution, the serifs "blur" in front of the eye, they appear pixelated and the font appears rather blurred to the eye. This effect is particularly noticeable with small font sizes.

It is therefore advisable to use sans-serif fonts for longer texts on screens. This significantly minimizes reading fatigue and the font often appears more modern and cleaner.

**Comment by akashar13** [comment]
@NoemieSch  https://github.com/learning-zone/website-templates/pull/52 . Please review and close this

**Comment by learning-zone** [comment]
Since these templates are licensed, we are not supposed to edit the existing templates
