### ISSUE TITLE
License Clarification Request

### ISSUE THREAD

**Issue by MyDataSci** [learning-zone/website-templates#57]
Hi! I noticed this repository doesn't have a license file.  Adding a license would be helpful for anyone interested in using the code.  Here's a resource to help choose a license: https://choosealicense.com/.

**Comment by GuilhermeLimaSP** [comment]
License file needed...

**Comment by zcraber** [comment]
@learning-zone Any update on this?

**Comment by Enzyklopaedie** [comment]
@learning-zone Under what license can we use the provided website templates?

**Comment by learning-zone** [comment]
Each template has its own license.

**Comment by zcraber** [comment]
> Each template has its own license.

Many of the templates don't have any license mentioned.
